void main() {
  int b = 10;
  //print(a);
  print(b);
  num value = 10.78;
  //   value="hi";
  print(value);
  print(value.runtimeType);
  var a = 10;
  a = 20;
  //a="hi";
  print(a);
  //int x=100;
  dynamic y = 90;
  print(y.runtimeType);
  y = "welcome";
  print(y.runtimeType);
  print(y);
  Object h = 10;
  print(h.runtimeType);
  print(h);
  h = "object data";
  print(h.runtimeType);
  print(h);
  h = [1, 2, 3];
  print(h);
  var s = "hi sai!";
  print(s);
  print(s.runtimeType);
  //num s1="hi bro!"; //we can't assign
  bool x = true;
  print(x);
  print(x.runtimeType);
  x = false;
  print(x);
  num z = 12.23;
  print(z);
  print(z.runtimeType);
  double c = 12.34;
  print(c.runtimeType);
  print(c);
  c = 12;
  print(c);
  print(c.runtimeType);
  String s12 = "harsha";
  print(s12);
  print(s12.runtimeType);
  s12 = s12 + "!";
  print(s12);
}
